const plugin = require("tailwindcss/plugin");

const unityTailwindPlugin = plugin(function ({ addBase }) {
  addBase({
    ":root": {
      "--uy-colors-grayscale-L0": "255 255 255",
      "--uy-colors-grayscale-L1": "252 252 253",
      "--uy-colors-grayscale-L2": "249 249 251",
      "--uy-colors-grayscale-L3": "240 240 243",
      "--uy-colors-grayscale-L4": "232 232 236",
      "--uy-colors-grayscale-L5": "224 225 230",
      "--uy-colors-grayscale-L6": "217 217 224",
      "--uy-colors-grayscale-L7": "205 206 214",
      "--uy-colors-grayscale-L8": "185 187 198",
      "--uy-colors-grayscale-L9": "139 141 152",
      "--uy-colors-grayscale-L10": "128 131 141",
      "--uy-colors-grayscale-L11": "96 100 108",
      "--uy-colors-grayscale-L12": "28 32 36",
      "--uy-colors-blue-L1": "253 253 254",
      "--uy-colors-blue-L2": "248 249 253",
      "--uy-colors-blue-L3": "235 244 255",
      "--uy-colors-blue-L4": "217 233 255",
      "--uy-colors-blue-L5": "214 221 251",
      "--uy-colors-blue-L6": "196 207 251",
      "--uy-colors-blue-L7": "170 189 253",
      "--uy-colors-blue-L8": "131 165 253",
      "--uy-colors-blue-L9": "15 111 222",
      "--uy-colors-blue-L10": "12 97 195",
      "--uy-colors-blue-L11": "1 87 178",
      "--uy-colors-blue-L12": "8 47 99",
      "--uy-colors-red-L1": "255 252 252",
      "--uy-colors-red-L2": "255 247 247",
      "--uy-colors-red-L3": "254 235 236",
      "--uy-colors-red-L4": "255 219 220",
      "--uy-colors-red-L5": "255 205 206",
      "--uy-colors-red-L6": "253 189 190",
      "--uy-colors-red-L7": "244 169 170",
      "--uy-colors-red-L8": "235 142 144",
      "--uy-colors-red-L9": "229 72 77",
      "--uy-colors-red-L10": "220 62 66",
      "--uy-colors-red-L11": "206 44 49",
      "--uy-colors-red-L12": "100 23 35",
      "--uy-colors-green-L1": "251 254 251",
      "--uy-colors-green-L2": "245 251 245",
      "--uy-colors-green-L3": "233 246 233",
      "--uy-colors-green-L4": "218 241 219",
      "--uy-colors-green-L5": "201 232 202",
      "--uy-colors-green-L6": "178 221 181",
      "--uy-colors-green-L7": "148 206 154",
      "--uy-colors-green-L8": "101 186 116",
      "--uy-colors-green-L9": "70 167 88",
      "--uy-colors-green-L10": "62 155 79",
      "--uy-colors-green-L11": "42 126 59",
      "--uy-colors-green-L12": "32 60 37",
      "--uy-colors-orange-L1": "254 252 251",
      "--uy-colors-orange-L2": "255 247 237",
      "--uy-colors-orange-L3": "255 239 214",
      "--uy-colors-orange-L4": "255 223 181",
      "--uy-colors-orange-L5": "255 209 154",
      "--uy-colors-orange-L6": "255 193 130",
      "--uy-colors-orange-L7": "245 174 115",
      "--uy-colors-orange-L8": "236 148 85",
      "--uy-colors-orange-L9": "247 107 21",
      "--uy-colors-orange-L10": "239 95 0",
      "--uy-colors-orange-L11": "204 78 0",
      "--uy-colors-orange-L12": "88 45 29",
      "--uy-colors-cyan-L1": "250 253 254",
      "--uy-colors-cyan-L2": "242 250 251",
      "--uy-colors-cyan-L3": "222 247 249",
      "--uy-colors-cyan-L4": "202 241 246",
      "--uy-colors-cyan-L5": "181 233 240",
      "--uy-colors-cyan-L6": "157 221 231",
      "--uy-colors-cyan-L7": "125 206 220",
      "--uy-colors-cyan-L8": "61 185 207",
      "--uy-colors-cyan-L9": "0 162 199",
      "--uy-colors-cyan-L10": "7 151 185",
      "--uy-colors-cyan-L11": "16 125 152",
      "--uy-colors-cyan-L12": "13 60 72",
      "--uy-colors-purple-L1": "253 253 254",
      "--uy-colors-purple-L2": "250 247 254",
      "--uy-colors-purple-L3": "245 239 253",
      "--uy-colors-purple-L4": "238 226 252",
      "--uy-colors-purple-L5": "231 217 248",
      "--uy-colors-purple-L6": "221 200 247",
      "--uy-colors-purple-L7": "213 175 253",
      "--uy-colors-purple-L8": "196 151 243",
      "--uy-colors-purple-L9": "146 79 230",
      "--uy-colors-purple-L10": "123 77 186",
      "--uy-colors-purple-L11": "108 68 164",
      "--uy-colors-purple-L12": "60 23 102",
      "--uy-colors-plum-L1": "254 252 255",
      "--uy-colors-plum-L2": "253 247 253",
      "--uy-colors-plum-L3": "251 235 251",
      "--uy-colors-plum-L4": "247 222 248",
      "--uy-colors-plum-L5": "242 209 243",
      "--uy-colors-plum-L6": "233 194 236",
      "--uy-colors-plum-L7": "222 173 227",
      "--uy-colors-plum-L8": "207 145 216",
      "--uy-colors-plum-L9": "171 74 186",
      "--uy-colors-plum-L10": "161 68 175",
      "--uy-colors-plum-L11": "149 62 163",
      "--uy-colors-plum-L12": "83 25 93",
      "--uy-colors-peach-L1": "255 243 240",
      "--uy-colors-peach-L2": "255 213 204",
      "--uy-colors-peach-L3": "255 172 153",
      "--uy-colors-peach-L9": "255 134 107",
      "--uy-colors-peach-L10": "255 88 51",
      "--uy-colors-peach-L11": "151 42 17",
      "--uy-colors-peach-L12": "56 10 0",
      "--uy-colors-sunglow-L1": "255 247 230",
      "--uy-colors-sunglow-L2": "255 235 194",
      "--uy-colors-sunglow-L3": "255 212 112",
      "--uy-colors-sunglow-L9": "255 182 10",
      "--uy-colors-sunglow-L10": "142 109 31",
      "--uy-colors-sunglow-L11": "94 71 19",
      "--uy-colors-sunglow-L12": "56 39 0",
      "--uy-colors-canvas": "var(--uy-colors-grayscale-L2)",
      "--uy-colors-surface-primary-highest": "var(--uy-colors-blue-L12)",
      "--uy-colors-surface-primary-high": "var(--uy-colors-blue-L11)",
      "--uy-colors-surface-primary": "var(--uy-colors-blue-L9)",
      "--uy-colors-surface-primary-enabled": "var(--uy-colors-blue-L9)",
      "--uy-colors-surface-primary-hover": "var(--uy-colors-blue-L10)",
      "--uy-colors-surface-primary-pressed": "var(--uy-colors-blue-L11)",
      "--uy-colors-surface-primary-focus": "var(--uy-colors-blue-L9)",
      "--uy-colors-surface-primary-active": "var(--uy-colors-blue-L11)",
      "--uy-colors-surface-primary-disabled": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-surface-primary-low": "var(--uy-colors-blue-L4)",
      "--uy-colors-surface-primary-lowest": "var(--uy-colors-blue-L3)",
      "--uy-colors-surface-primary-lowest-enabled": "var(--uy-colors-blue-L3)",
      "--uy-colors-surface-primary-lowest-hover": "var(--uy-colors-blue-L3)",
      "--uy-colors-surface-primary-lowest-pressed": "var(--uy-colors-blue-L3)",
      "--uy-colors-surface-primary-lowest-focus": "var(--uy-colors-blue-L3)",
      "--uy-colors-surface-primary-lowest-active": "var(--uy-colors-blue-L3)",
      "--uy-colors-surface-primary-lowest-disabled":
        "var(--uy-colors-grayscale-L2)",
      "--uy-colors-surface-neutral": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-neutral-enabled": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-neutral-hover": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-surface-neutral-pressed": "var(--uy-colors-grayscale-L4)",
      "--uy-colors-surface-neutral-focus": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-neutral-active": "var(--uy-colors-grayscale-L4)",
      "--uy-colors-surface-neutral-disabled": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-surface-neutral-low": "var(--uy-colors-grayscale-L1)",
      "--uy-colors-surface-neutral-lowest": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-surface-danger": "var(--uy-colors-red-L9)",
      "--uy-colors-surface-danger-enabled": "var(--uy-colors-red-L9)",
      "--uy-colors-surface-danger-hover": "var(--uy-colors-red-L10)",
      "--uy-colors-surface-danger-pressed": "var(--uy-colors-red-L11)",
      "--uy-colors-surface-danger-focus": "var(--uy-colors-red-L9)",
      "--uy-colors-surface-danger-active": "var(--uy-colors-red-L11)",
      "--uy-colors-surface-danger-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-danger-low": "var(--uy-colors-red-L4)",
      "--uy-colors-surface-danger-lowest": "var(--uy-colors-red-L2)",
      "--uy-colors-surface-danger-lowest-enabled": "var(--uy-colors-red-L3)",
      "--uy-colors-surface-danger-lowest-hover": "var(--uy-colors-red-L3)",
      "--uy-colors-surface-danger-lowest-pressed": "var(--uy-colors-red-L3)",
      "--uy-colors-surface-danger-lowest-focus": "var(--uy-colors-red-L3)",
      "--uy-colors-surface-danger-lowest-active": "var(--uy-colors-red-L3)",
      "--uy-colors-surface-danger-lowest-disabled":
        "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-warning": "var(--uy-colors-orange-L9)",
      "--uy-colors-surface-warning-enabled": "var(--uy-colors-orange-L9)",
      "--uy-colors-surface-warning-hover": "var(--uy-colors-orange-L10)",
      "--uy-colors-surface-warning-pressed": "var(--uy-colors-orange-L11)",
      "--uy-colors-surface-warning-focus": "var(--uy-colors-orange-L9)",
      "--uy-colors-surface-warning-active": "var(--uy-colors-orange-L11)",
      "--uy-colors-surface-warning-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-warning-low": "var(--uy-colors-orange-L4)",
      "--uy-colors-surface-warning-lowest": "var(--uy-colors-orange-L2)",
      "--uy-colors-surface-warning-lowest-enabled":
        "var(--uy-colors-orange-L3)",
      "--uy-colors-surface-warning-lowest-hover": "var(--uy-colors-orange-L3)",
      "--uy-colors-surface-warning-lowest-pressed":
        "var(--uy-colors-orange-L3)",
      "--uy-colors-surface-warning-lowest-focus": "var(--uy-colors-orange-L3)",
      "--uy-colors-surface-warning-lowest-active": "var(--uy-colors-orange-L3)",
      "--uy-colors-surface-warning-lowest-disabled":
        "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-success": "var(--uy-colors-green-L9)",
      "--uy-colors-surface-success-low": "var(--uy-colors-green-L4)",
      "--uy-colors-surface-success-lowest": "var(--uy-colors-green-L2)",
      "--uy-colors-surface-success-lowest-enabled": "var(--uy-colors-green-L2)",
      "--uy-colors-surface-success-lowest-hover": "var(--uy-colors-green-L3)",
      "--uy-colors-surface-success-lowest-pressed": "var(--uy-colors-green-L3)",
      "--uy-colors-surface-success-lowest-focus": "var(--uy-colors-green-L9)",
      "--uy-colors-surface-success-lowest-active": "var(--uy-colors-green-L11)",
      "--uy-colors-surface-success-lowest-disabled":
        "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-info": "var(--uy-colors-cyan-L9)",
      "--uy-colors-surface-info-low": "var(--uy-colors-cyan-L4)",
      "--uy-colors-surface-info-lowest": "var(--uy-colors-cyan-L2)",
      "--uy-colors-surface-info-lowest-enabled": "var(--uy-colors-cyan-L2)",
      "--uy-colors-surface-info-lowest-hover": "var(--uy-colors-cyan-L3)",
      "--uy-colors-surface-info-lowest-pressed": "var(--uy-colors-cyan-L3)",
      "--uy-colors-surface-info-lowest-focus": "var(--uy-colors-cyan-L9)",
      "--uy-colors-surface-info-lowest-active": "var(--uy-colors-cyan-L11)",
      "--uy-colors-surface-info-lowest-disabled":
        "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-promo": "var(--uy-colors-plum-L9)",
      "--uy-colors-surface-promo-low": "var(--uy-colors-plum-L4)",
      "--uy-colors-surface-ai-low": "var(--uy-colors-purple-L4)",
      "--uy-colors-surface-form-enabled": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-form-hover": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-form-pressed": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-form-focus": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-form-active": "var(--uy-colors-blue-L11)",
      "--uy-colors-surface-form-disabled": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-surface-form-read-only": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-surface-form-error": "var(--uy-colors-red-L2)",
      "--uy-colors-surface-inverted": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-inverted-enabled": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-inverted-hover": "var(--uy-colors-grayscale-L2)",
      "--uy-colors-surface-inverted-pressed": "var(--uy-colors-grayscale-L4)",
      "--uy-colors-surface-inverted-focus": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-inverted-active": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-surface-inverted-disabled": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-content-primary": "var(--uy-colors-blue-L9)",
      "--uy-colors-content-primary-enabled": "var(--uy-colors-blue-L9)",
      "--uy-colors-content-primary-hover": "var(--uy-colors-blue-L10)",
      "--uy-colors-content-primary-pressed": "var(--uy-colors-blue-L11)",
      "--uy-colors-content-primary-focus": "var(--uy-colors-blue-L9)",
      "--uy-colors-content-primary-active": "var(--uy-colors-blue-L11)",
      "--uy-colors-content-primary-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-neutral": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-enabled": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-hover": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-pressed": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-focus": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-active": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-neutral-low": "var(--uy-colors-grayscale-L11)",
      "--uy-colors-content-neutral-lowest": "var(--uy-colors-grayscale-L9)",
      "--uy-colors-content-neutral-lowest-enabled":
        "var(--uy-colors-grayscale-L9)",
      "--uy-colors-content-neutral-lowest-hover":
        "var(--uy-colors-grayscale-L10)",
      "--uy-colors-content-neutral-lowest-pressed":
        "var(--uy-colors-grayscale-L11)",
      "--uy-colors-content-neutral-lowest-focus":
        "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-lowest-active":
        "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-neutral-lowest-disabled":
        "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-danger": "var(--uy-colors-red-L9)",
      "--uy-colors-content-danger-enabled": "var(--uy-colors-red-L9)",
      "--uy-colors-content-danger-hover": "var(--uy-colors-red-L10)",
      "--uy-colors-content-danger-pressed": "var(--uy-colors-red-L11)",
      "--uy-colors-content-danger-focus": "var(--uy-colors-red-L9)",
      "--uy-colors-content-danger-active": "var(--uy-colors-red-L11)",
      "--uy-colors-content-danger-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-warning": "var(--uy-colors-orange-L9)",
      "--uy-colors-content-warning-enabled": "var(--uy-colors-orange-L9)",
      "--uy-colors-content-warning-hover": "var(--uy-colors-orange-L10)",
      "--uy-colors-content-warning-pressed": "var(--uy-colors-orange-L11)",
      "--uy-colors-content-warning-focus": "var(--uy-colors-orange-L9)",
      "--uy-colors-content-warning-active": "var(--uy-colors-orange-L11)",
      "--uy-colors-content-warning-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-success": "var(--uy-colors-green-L9)",
      "--uy-colors-content-success-enabled": "var(--uy-colors-green-L9)",
      "--uy-colors-content-success-hover": "var(--uy-colors-green-L10)",
      "--uy-colors-content-success-pressed": "var(--uy-colors-green-L11)",
      "--uy-colors-content-success-focus": "var(--uy-colors-green-L9)",
      "--uy-colors-content-success-active": "var(--uy-colors-green-L11)",
      "--uy-colors-content-success-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-info": "var(--uy-colors-cyan-L9)",
      "--uy-colors-content-info-enabled": "var(--uy-colors-cyan-L9)",
      "--uy-colors-content-info-hover": "var(--uy-colors-cyan-L10)",
      "--uy-colors-content-info-pressed": "var(--uy-colors-cyan-L11)",
      "--uy-colors-content-info-focus": "var(--uy-colors-cyan-L9)",
      "--uy-colors-content-info-active": "var(--uy-colors-cyan-L11)",
      "--uy-colors-content-info-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-promo": "var(--uy-colors-plum-L9)",
      "--uy-colors-content-form-enabled": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-form-hover": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-form-pressed": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-form-focus": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-form-active": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-form-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-content-form-read-only": "var(--uy-colors-grayscale-L12)",
      "--uy-colors-content-form-invalid": "var(--uy-colors-red-L9)",
      "--uy-colors-content-inverted": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-content-inverted-enabled": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-content-inverted-hover": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-content-inverted-pressed": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-content-inverted-focus": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-content-inverted-active": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-content-inverted-disabled": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-border-primary": "var(--uy-colors-blue-L9)",
      "--uy-colors-border-primary-enabled": "var(--uy-colors-blue-L9)",
      "--uy-colors-border-primary-hover": "var(--uy-colors-blue-L10)",
      "--uy-colors-border-primary-pressed": "var(--uy-colors-blue-L11)",
      "--uy-colors-border-primary-focus": "var(--uy-colors-blue-L9)",
      "--uy-colors-border-primary-active": "var(--uy-colors-blue-L11)",
      "--uy-colors-border-primary-disabled": "var(--uy-colors-grayscale-L5)",
      "--uy-colors-border-neutral-high": "var(--uy-colors-grayscale-L6)",
      "--uy-colors-border-neutral": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-border-neutral-disabled": "var(--uy-colors-grayscale-L5)",
      "--uy-colors-border-danger": "var(--uy-colors-red-L9)",
      "--uy-colors-border-danger-lowest": "var(--uy-colors-red-L6)",
      "--uy-colors-border-warning": "var(--uy-colors-orange-L9)",
      "--uy-colors-border-warning-lowest": "var(--uy-colors-orange-L6)",
      "--uy-colors-border-success": "var(--uy-colors-green-L9)",
      "--uy-colors-border-success-lowest": "var(--uy-colors-green-L6)",
      "--uy-colors-border-info": "var(--uy-colors-cyan-L9)",
      "--uy-colors-border-info-lowest": "var(--uy-colors-cyan-L6)",
      "--uy-colors-border-promo": "var(--uy-colors-plum-L9)",
      "--uy-colors-border-promo-lowest": "var(--uy-colors-plum-L6)",
      "--uy-colors-border-form-enabled": "var(--uy-colors-grayscale-L7)",
      "--uy-colors-border-form-hover": "var(--uy-colors-grayscale-L8)",
      "--uy-colors-border-form-pressed": "var(--uy-colors-grayscale-L9)",
      "--uy-colors-border-form-focus": "var(--uy-colors-grayscale-L7)",
      "--uy-colors-border-form-active": "var(--uy-colors-blue-L11)",
      "--uy-colors-border-form-disabled": "var(--uy-colors-grayscale-L5)",
      "--uy-colors-border-form-read-only": "var(--uy-colors-grayscale-L5)",
      "--uy-colors-border-form-error": "var(--uy-colors-red-L6)",
      "--uy-colors-border-inverted": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-border-inverted-enabled": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-border-inverted-hover": "var(--uy-colors-grayscale-L2)",
      "--uy-colors-border-inverted-pressed": "var(--uy-colors-grayscale-L4)",
      "--uy-colors-border-inverted-focus": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-border-inverted-active": "var(--uy-colors-grayscale-L0)",
      "--uy-colors-border-inverted-disabled": "var(--uy-colors-grayscale-L3)",
      "--uy-colors-utility-focus-ring": "var(--uy-colors-blue-L12)",
      "--uy-colors-utility-inverted-focus-ring": "var(--uy-colors-sunglow-L3)",
      "--uy-colors-utility-backdrop": "rgba(28, 32, 36, 0.64)",
      "--uy-radius-0": "0",
      "--uy-radius-25": "0.125rem",
      "--uy-radius-50": "0.25rem",
      "--uy-radius-75": "0.375rem",
      "--uy-radius-100": "0.5rem",
      "--uy-radius-125": "0.625rem",
      "--uy-radius-150": "0.75rem",
      "--uy-radius-200": "1rem",
      "--uy-radius-300": "1.5rem",
      "--uy-radius-400": "2rem",
      "--uy-radius-circle": "50px",
      "--uy-radius-pill": "9999px",
      "--uy-shadow-canvas": "none",
      "--uy-shadow-raising": "0px 1px 2px 0px #04204010",
      "--uy-shadow-floating": "0px 6px 20px -4px #04204014",
      "--uy-shadow-flying": "0px 12px 24px -6px #0420401a",
      "--uy-shadow-soaring": "0px 24px 32px -8px #0420401f",
      "--uy-spacing-0": "0",
      "--uy-spacing-25": "0.125rem",
      "--uy-spacing-50": "0.25rem",
      "--uy-spacing-75": "0.375rem",
      "--uy-spacing-100": "0.5rem",
      "--uy-spacing-125": "0.625rem",
      "--uy-spacing-150": "0.75rem",
      "--uy-spacing-200": "1rem",
      "--uy-spacing-250": "1.25rem",
      "--uy-spacing-300": "1.5rem",
      "--uy-spacing-400": "2rem",
      "--uy-spacing-500": "2.5rem",
      "--uy-spacing-600": "3rem",
      "--uy-spacing-800": "4rem",
      "--uy-spacing-1000": "5rem",
      "--uy-font-family-serif": "Source Serif 4",
      "--uy-font-family-sans": "Inter",
      "--uy-font-size-50": "0.75rem",
      "--uy-font-size-75": "0.875rem",
      "--uy-font-size-100": "1rem",
      "--uy-font-size-125": "1.125rem",
      "--uy-font-size-150": "1.5rem",
      "--uy-font-size-175": "1.75rem",
      "--uy-font-weight-regular": 400,
      "--uy-font-weight-medium": 500,
      "--uy-font-weight-semibold": 600,
      "--uy-font-weight-bold": 700,
      "--uy-font-lineHeight-100": 1,
      "--uy-font-lineHeight-125": 1.25,
      "--uy-font-lineHeight-150": 1.5,
      "--uy-font-lineHeight-175": 1.75,
    },
  });
});

const preset = {
  theme: {
    colors: {
      grayscale: {
        L0: "rgb(var(--uy-colors-grayscale-L0) / <alpha-value>)",
        L1: "rgb(var(--uy-colors-grayscale-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-grayscale-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-grayscale-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-grayscale-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-grayscale-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-grayscale-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-grayscale-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-grayscale-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-grayscale-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-grayscale-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-grayscale-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-grayscale-L12) / <alpha-value>)",
      },
      blue: {
        L1: "rgb(var(--uy-colors-blue-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-blue-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-blue-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-blue-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-blue-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-blue-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-blue-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-blue-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-blue-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-blue-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-blue-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-blue-L12) / <alpha-value>)",
      },
      red: {
        L1: "rgb(var(--uy-colors-red-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-red-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-red-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-red-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-red-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-red-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-red-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-red-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-red-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-red-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-red-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-red-L12) / <alpha-value>)",
      },
      green: {
        L1: "rgb(var(--uy-colors-green-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-green-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-green-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-green-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-green-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-green-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-green-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-green-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-green-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-green-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-green-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-green-L12) / <alpha-value>)",
      },
      orange: {
        L1: "rgb(var(--uy-colors-orange-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-orange-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-orange-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-orange-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-orange-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-orange-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-orange-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-orange-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-orange-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-orange-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-orange-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-orange-L12) / <alpha-value>)",
      },
      cyan: {
        L1: "rgb(var(--uy-colors-cyan-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-cyan-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-cyan-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-cyan-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-cyan-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-cyan-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-cyan-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-cyan-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-cyan-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-cyan-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-cyan-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-cyan-L12) / <alpha-value>)",
      },
      purple: {
        L1: "rgb(var(--uy-colors-purple-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-purple-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-purple-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-purple-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-purple-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-purple-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-purple-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-purple-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-purple-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-purple-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-purple-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-purple-L12) / <alpha-value>)",
      },
      plum: {
        L1: "rgb(var(--uy-colors-plum-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-plum-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-plum-L3) / <alpha-value>)",
        L4: "rgb(var(--uy-colors-plum-L4) / <alpha-value>)",
        L5: "rgb(var(--uy-colors-plum-L5) / <alpha-value>)",
        L6: "rgb(var(--uy-colors-plum-L6) / <alpha-value>)",
        L7: "rgb(var(--uy-colors-plum-L7) / <alpha-value>)",
        L8: "rgb(var(--uy-colors-plum-L8) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-plum-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-plum-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-plum-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-plum-L12) / <alpha-value>)",
      },
      peach: {
        L1: "rgb(var(--uy-colors-peach-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-peach-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-peach-L3) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-peach-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-peach-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-peach-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-peach-L12) / <alpha-value>)",
      },
      sunglow: {
        L1: "rgb(var(--uy-colors-sunglow-L1) / <alpha-value>)",
        L2: "rgb(var(--uy-colors-sunglow-L2) / <alpha-value>)",
        L3: "rgb(var(--uy-colors-sunglow-L3) / <alpha-value>)",
        L9: "rgb(var(--uy-colors-sunglow-L9) / <alpha-value>)",
        L10: "rgb(var(--uy-colors-sunglow-L10) / <alpha-value>)",
        L11: "rgb(var(--uy-colors-sunglow-L11) / <alpha-value>)",
        L12: "rgb(var(--uy-colors-sunglow-L12) / <alpha-value>)",
      },
      canvas: {
        DEFAULT: "rgb(var(--uy-colors-canvas) / <alpha-value>)",
      },
      surface: {
        primary: {
          highest:
            "rgb(var(--uy-colors-surface-primary-highest) / <alpha-value>)",
          high: "rgb(var(--uy-colors-surface-primary-high) / <alpha-value>)",
          DEFAULT: "rgb(var(--uy-colors-surface-primary) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-surface-primary-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-surface-primary-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-surface-primary-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-surface-primary-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-surface-primary-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-surface-primary-disabled) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-primary-low) / <alpha-value>)",
          lowest: {
            DEFAULT:
              "rgb(var(--uy-colors-surface-primary-lowest) / <alpha-value>)",
            enabled:
              "rgb(var(--uy-colors-surface-primary-lowest-enabled) / <alpha-value>)",
            hover:
              "rgb(var(--uy-colors-surface-primary-lowest-hover) / <alpha-value>)",
            pressed:
              "rgb(var(--uy-colors-surface-primary-lowest-pressed) / <alpha-value>)",
            focus:
              "rgb(var(--uy-colors-surface-primary-lowest-focus) / <alpha-value>)",
            active:
              "rgb(var(--uy-colors-surface-primary-lowest-active) / <alpha-value>)",
            disabled:
              "rgb(var(--uy-colors-surface-primary-lowest-disabled) / <alpha-value>)",
          },
        },
        neutral: {
          DEFAULT: "rgb(var(--uy-colors-surface-neutral) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-surface-neutral-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-surface-neutral-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-surface-neutral-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-surface-neutral-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-surface-neutral-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-surface-neutral-disabled) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-neutral-low) / <alpha-value>)",
          lowest:
            "rgb(var(--uy-colors-surface-neutral-lowest) / <alpha-value>)",
        },
        danger: {
          DEFAULT: "rgb(var(--uy-colors-surface-danger) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-surface-danger-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-surface-danger-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-surface-danger-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-surface-danger-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-surface-danger-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-surface-danger-disabled) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-danger-low) / <alpha-value>)",
          lowest: {
            DEFAULT:
              "rgb(var(--uy-colors-surface-danger-lowest) / <alpha-value>)",
            enabled:
              "rgb(var(--uy-colors-surface-danger-lowest-enabled) / <alpha-value>)",
            hover:
              "rgb(var(--uy-colors-surface-danger-lowest-hover) / <alpha-value>)",
            pressed:
              "rgb(var(--uy-colors-surface-danger-lowest-pressed) / <alpha-value>)",
            focus:
              "rgb(var(--uy-colors-surface-danger-lowest-focus) / <alpha-value>)",
            active:
              "rgb(var(--uy-colors-surface-danger-lowest-active) / <alpha-value>)",
            disabled:
              "rgb(var(--uy-colors-surface-danger-lowest-disabled) / <alpha-value>)",
          },
        },
        warning: {
          DEFAULT: "rgb(var(--uy-colors-surface-warning) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-surface-warning-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-surface-warning-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-surface-warning-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-surface-warning-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-surface-warning-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-surface-warning-disabled) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-warning-low) / <alpha-value>)",
          lowest: {
            DEFAULT:
              "rgb(var(--uy-colors-surface-warning-lowest) / <alpha-value>)",
            enabled:
              "rgb(var(--uy-colors-surface-warning-lowest-enabled) / <alpha-value>)",
            hover:
              "rgb(var(--uy-colors-surface-warning-lowest-hover) / <alpha-value>)",
            pressed:
              "rgb(var(--uy-colors-surface-warning-lowest-pressed) / <alpha-value>)",
            focus:
              "rgb(var(--uy-colors-surface-warning-lowest-focus) / <alpha-value>)",
            active:
              "rgb(var(--uy-colors-surface-warning-lowest-active) / <alpha-value>)",
            disabled:
              "rgb(var(--uy-colors-surface-warning-lowest-disabled) / <alpha-value>)",
          },
        },
        success: {
          DEFAULT: "rgb(var(--uy-colors-surface-success) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-success-low) / <alpha-value>)",
          lowest: {
            DEFAULT:
              "rgb(var(--uy-colors-surface-success-lowest) / <alpha-value>)",
            enabled:
              "rgb(var(--uy-colors-surface-success-lowest-enabled) / <alpha-value>)",
            hover:
              "rgb(var(--uy-colors-surface-success-lowest-hover) / <alpha-value>)",
            pressed:
              "rgb(var(--uy-colors-surface-success-lowest-pressed) / <alpha-value>)",
            focus:
              "rgb(var(--uy-colors-surface-success-lowest-focus) / <alpha-value>)",
            active:
              "rgb(var(--uy-colors-surface-success-lowest-active) / <alpha-value>)",
            disabled:
              "rgb(var(--uy-colors-surface-success-lowest-disabled) / <alpha-value>)",
          },
        },
        info: {
          DEFAULT: "rgb(var(--uy-colors-surface-info) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-info-low) / <alpha-value>)",
          lowest: {
            DEFAULT:
              "rgb(var(--uy-colors-surface-info-lowest) / <alpha-value>)",
            enabled:
              "rgb(var(--uy-colors-surface-info-lowest-enabled) / <alpha-value>)",
            hover:
              "rgb(var(--uy-colors-surface-info-lowest-hover) / <alpha-value>)",
            pressed:
              "rgb(var(--uy-colors-surface-info-lowest-pressed) / <alpha-value>)",
            focus:
              "rgb(var(--uy-colors-surface-info-lowest-focus) / <alpha-value>)",
            active:
              "rgb(var(--uy-colors-surface-info-lowest-active) / <alpha-value>)",
            disabled:
              "rgb(var(--uy-colors-surface-info-lowest-disabled) / <alpha-value>)",
          },
        },
        promo: {
          DEFAULT: "rgb(var(--uy-colors-surface-promo) / <alpha-value>)",
          low: "rgb(var(--uy-colors-surface-promo-low) / <alpha-value>)",
        },
        ai: {
          low: "rgb(var(--uy-colors-surface-ai-low) / <alpha-value>)",
        },
        form: {
          enabled: "rgb(var(--uy-colors-surface-form-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-surface-form-hover) / <alpha-value>)",
          pressed: "rgb(var(--uy-colors-surface-form-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-surface-form-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-surface-form-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-surface-form-disabled) / <alpha-value>)",
          "read-only":
            "rgb(var(--uy-colors-surface-form-read-only) / <alpha-value>)",
          error: "rgb(var(--uy-colors-surface-form-error) / <alpha-value>)",
        },
        inverted: {
          DEFAULT: "rgb(var(--uy-colors-surface-inverted) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-surface-inverted-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-surface-inverted-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-surface-inverted-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-surface-inverted-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-surface-inverted-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-surface-inverted-disabled) / <alpha-value>)",
        },
      },
      content: {
        primary: {
          DEFAULT: "rgb(var(--uy-colors-content-primary) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-content-primary-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-primary-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-content-primary-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-primary-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-content-primary-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-primary-disabled) / <alpha-value>)",
        },
        neutral: {
          DEFAULT: "rgb(var(--uy-colors-content-neutral) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-content-neutral-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-neutral-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-content-neutral-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-neutral-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-content-neutral-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-neutral-disabled) / <alpha-value>)",
          low: "rgb(var(--uy-colors-content-neutral-low) / <alpha-value>)",
          lowest: {
            DEFAULT:
              "rgb(var(--uy-colors-content-neutral-lowest) / <alpha-value>)",
            enabled:
              "rgb(var(--uy-colors-content-neutral-lowest-enabled) / <alpha-value>)",
            hover:
              "rgb(var(--uy-colors-content-neutral-lowest-hover) / <alpha-value>)",
            pressed:
              "rgb(var(--uy-colors-content-neutral-lowest-pressed) / <alpha-value>)",
            focus:
              "rgb(var(--uy-colors-content-neutral-lowest-focus) / <alpha-value>)",
            active:
              "rgb(var(--uy-colors-content-neutral-lowest-active) / <alpha-value>)",
            disabled:
              "rgb(var(--uy-colors-content-neutral-lowest-disabled) / <alpha-value>)",
          },
        },
        danger: {
          DEFAULT: "rgb(var(--uy-colors-content-danger) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-content-danger-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-danger-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-content-danger-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-danger-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-content-danger-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-danger-disabled) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--uy-colors-content-warning) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-content-warning-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-warning-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-content-warning-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-warning-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-content-warning-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-warning-disabled) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--uy-colors-content-success) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-content-success-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-success-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-content-success-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-success-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-content-success-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-success-disabled) / <alpha-value>)",
        },
        info: {
          DEFAULT: "rgb(var(--uy-colors-content-info) / <alpha-value>)",
          enabled: "rgb(var(--uy-colors-content-info-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-info-hover) / <alpha-value>)",
          pressed: "rgb(var(--uy-colors-content-info-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-info-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-content-info-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-info-disabled) / <alpha-value>)",
        },
        promo: "rgb(var(--uy-colors-content-promo) / <alpha-value>)",
        form: {
          enabled: "rgb(var(--uy-colors-content-form-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-form-hover) / <alpha-value>)",
          pressed: "rgb(var(--uy-colors-content-form-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-form-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-content-form-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-form-disabled) / <alpha-value>)",
          "read-only":
            "rgb(var(--uy-colors-content-form-read-only) / <alpha-value>)",
          invalid: "rgb(var(--uy-colors-content-form-invalid) / <alpha-value>)",
        },
        inverted: {
          DEFAULT: "rgb(var(--uy-colors-content-inverted) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-content-inverted-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-content-inverted-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-content-inverted-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-content-inverted-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-content-inverted-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-content-inverted-disabled) / <alpha-value>)",
        },
      },
      border: {
        primary: {
          DEFAULT: "rgb(var(--uy-colors-border-primary) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-border-primary-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-border-primary-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-border-primary-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-border-primary-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-border-primary-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-border-primary-disabled) / <alpha-value>)",
        },
        neutral: {
          high: "rgb(var(--uy-colors-border-neutral-high) / <alpha-value>)",
          DEFAULT: "rgb(var(--uy-colors-border-neutral) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-border-neutral-disabled) / <alpha-value>)",
        },
        danger: {
          DEFAULT: "rgb(var(--uy-colors-border-danger) / <alpha-value>)",
          lowest: "rgb(var(--uy-colors-border-danger-lowest) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--uy-colors-border-warning) / <alpha-value>)",
          lowest: "rgb(var(--uy-colors-border-warning-lowest) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--uy-colors-border-success) / <alpha-value>)",
          lowest: "rgb(var(--uy-colors-border-success-lowest) / <alpha-value>)",
        },
        info: {
          DEFAULT: "rgb(var(--uy-colors-border-info) / <alpha-value>)",
          lowest: "rgb(var(--uy-colors-border-info-lowest) / <alpha-value>)",
        },
        promo: {
          DEFAULT: "rgb(var(--uy-colors-border-promo) / <alpha-value>)",
          lowest: "rgb(var(--uy-colors-border-promo-lowest) / <alpha-value>)",
        },
        form: {
          enabled: "rgb(var(--uy-colors-border-form-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-border-form-hover) / <alpha-value>)",
          pressed: "rgb(var(--uy-colors-border-form-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-border-form-focus) / <alpha-value>)",
          active: "rgb(var(--uy-colors-border-form-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-border-form-disabled) / <alpha-value>)",
          "read-only":
            "rgb(var(--uy-colors-border-form-read-only) / <alpha-value>)",
          error: "rgb(var(--uy-colors-border-form-error) / <alpha-value>)",
        },
        inverted: {
          DEFAULT: "rgb(var(--uy-colors-border-inverted) / <alpha-value>)",
          enabled:
            "rgb(var(--uy-colors-border-inverted-enabled) / <alpha-value>)",
          hover: "rgb(var(--uy-colors-border-inverted-hover) / <alpha-value>)",
          pressed:
            "rgb(var(--uy-colors-border-inverted-pressed) / <alpha-value>)",
          focus: "rgb(var(--uy-colors-border-inverted-focus) / <alpha-value>)",
          active:
            "rgb(var(--uy-colors-border-inverted-active) / <alpha-value>)",
          disabled:
            "rgb(var(--uy-colors-border-inverted-disabled) / <alpha-value>)",
        },
      },
      utility: {
        "focus-ring":
          "rgb(var(--uy-colors-utility-focus-ring) / <alpha-value>)",
        "inverted-focus-ring":
          "rgb(var(--uy-colors-utility-inverted-focus-ring) / <alpha-value>)",
        backdrop: "rgb(var(--uy-colors-utility-backdrop) / <alpha-value>)",
      },
    },
    borderRadius: {
      0: "var(--uy-radius-0)",
      25: "var(--uy-radius-25)",
      50: "var(--uy-radius-50)",
      75: "var(--uy-radius-75)",
      100: "var(--uy-radius-100)",
      125: "var(--uy-radius-125)",
      150: "var(--uy-radius-150)",
      200: "var(--uy-radius-200)",
      300: "var(--uy-radius-300)",
      400: "var(--uy-radius-400)",
      circle: "var(--uy-radius-circle)",
      pill: "var(--uy-radius-pill)",
    },
    boxShadow: {
      canvas: "var(--uy-shadow-canvas)",
      raising: "var(--uy-shadow-raising)",
      floating: "var(--uy-shadow-floating)",
      flying: "var(--uy-shadow-flying)",
      soaring: "var(--uy-shadow-soaring)",
    },
    spacing: {
      0: "var(--uy-spacing-0)",
      25: "var(--uy-spacing-25)",
      50: "var(--uy-spacing-50)",
      75: "var(--uy-spacing-75)",
      100: "var(--uy-spacing-100)",
      125: "var(--uy-spacing-125)",
      150: "var(--uy-spacing-150)",
      200: "var(--uy-spacing-200)",
      250: "var(--uy-spacing-250)",
      300: "var(--uy-spacing-300)",
      400: "var(--uy-spacing-400)",
      500: "var(--uy-spacing-500)",
      600: "var(--uy-spacing-600)",
      800: "var(--uy-spacing-800)",
      1000: "var(--uy-spacing-1000)",
    },
    fontFamily: {
      serif: "var(--uy-font-family-serif)",
      sans: "var(--uy-font-family-sans)",
    },
    fontSize: {
      50: "var(--uy-font-size-50)",
      75: "var(--uy-font-size-75)",
      100: "var(--uy-font-size-100)",
      125: "var(--uy-font-size-125)",
      150: "var(--uy-font-size-150)",
      175: "var(--uy-font-size-175)",
    },
    fontWeight: {
      regular: "var(--uy-font-weight-regular)",
      medium: "var(--uy-font-weight-medium)",
      semibold: "var(--uy-font-weight-semibold)",
      bold: "var(--uy-font-weight-bold)",
    },
    lineHeight: {
      100: "var(--uy-font-lineHeight-100)",
      125: "var(--uy-font-lineHeight-125)",
      150: "var(--uy-font-lineHeight-150)",
      175: "var(--uy-font-lineHeight-175)",
    },
  },
};

/** @type {import('tailwindcss').Config} */
module.exports = {
  ...preset,
  plugins: [unityTailwindPlugin],
};
